
#define	COLLISION_HIDDEN_IN_GAME													false

#define MONSTER_AISENSECONFIG_SIGHT_SIGHTRADIUS										1000.f
#define MONSTER_AISENSECONFIG_SIGHT_LOSESIGHTRADIUS									1100.f
#define MONSTER_AISENSECONFIG_SIGHT_LOSESIGHTRADIUS_PERIPHERAL_VISIONANGLEDEGREES	120.f

#define DEFAULT_MESH_SCALE															45.f


#define MONSTER_CAMPFIRE_MIN_LENGTH													350.f